version: "0.0"

services:

  keycloak:
    image: quay.io/keycloak/keycloak:23.0.6
    container_name: keycloak
    ports:
      - 8080:8080
    environment:
      KEYCLOAK_ADMIN: "admin"
      KEYCLOAK_ADMIN_PASSWORD: "admin"
      # Configure database connection for Keycloak
      #KC_DB: mysql
      #KC_DB_URL: jdbc:mysql://mysql:3306/keycloak
      #KC_DB_USERNAME: keycloak
      #KC_DB_PASSWORD: keycloak
    command:  start-dev --import-realm
    networks:
      - keycloak-net
    volumes:
      - ./keycloak:/opt/keycloak/data/import




#volumes:

networks:
  keycloak-net:
    driver: bridge